apiVersion: v1
kind: Service
metadata:
  name: fastapi-heart
spec:
  type: LoadBalancer
  selector:
    app: fastapi-heart
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-heart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-heart
  template:
    metadata:
      labels:
        app: fastapi-heart
    spec:
      containers:
      - name: fastapi-heart
        image: jinorohit/heartpreds
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80