apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymongo
  template:
    metadata:
      labels:
        app: mymongo
    spec:
      containers:
      - name: mymongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: mymongo
spec:
  selector:
    app: mymongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
